In [9]:
import numpy as np

# Массив из обычного списка
arr_from_list = np.array([999, 998, 997, 888, 666])
print("Массив из списка:\n", arr_from_list)

# Массив из двумерного списка
arr_2d = np.array([[11, 22], [33, 44]])
print("Двумерный массив из списка:\n", arr_2d)

# Массив из нулей
zeros_arr = np.zeros(8)
print("Массив из нулей:\n", zeros_arr)

# Массив из единиц
ones_arr = np.ones(8)
print("Массив из единиц:\n", ones_arr)

# Массив с помощью arange
range_arr = np.arange(0, 10, 2)  # (0,10], шаг 2
print("Массив с помощью arange:\n", range_arr)

print("Форма массива arr_from_list:", arr_from_list.shape)
print("Тип данных массива arr_from_list:\n", arr_from_list.dtype)

# Получение отдельного элемента
element = arr_2d[0, 1] 
print("Элемент [0,1] в arr_2d:\n", element)

# Извлечение подмассива с помощью среза
subarray = arr_from_list[1:4]  # элементы с индексом от 1 до 3
print("Срез arr_from_list[1:4]:\n", subarray)

# Поэлементное сложение
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_result = a + b
print("Поэлементное сложение a + b:\n", sum_result)

# Поэлементное умножение
product_result = a * b
print("Поэлементное умножение a * b:\n", product_result)

# Вычисление среднего значения
mean_val = np.mean(a)
print("Среднее значение массива a:\n", mean_val)

# Вычисление медианы 
sum_val = np.median(b)
print("Медиана массива b:\n", sum_val)


Массив из списка:
 [999 998 997 888 666]
Двумерный массив из списка:
 [[11 22]
 [33 44]]
Массив из нулей:
 [0. 0. 0. 0. 0. 0. 0. 0.]
Массив из единиц:
 [1. 1. 1. 1. 1. 1. 1. 1.]
Массив с помощью arange:
 [0 2 4 6 8]
Форма массива arr_from_list: (5,)
Тип данных массива arr_from_list:
 int64
Элемент [0,1] в arr_2d:
 22
Срез arr_from_list[1:4]:
 [998 997 888]
Поэлементное сложение a + b:
 [5 7 9]
Поэлементное умножение a * b:
 [ 4 10 18]
Среднее значение массива a: 2.0
Сумма элементов массива b: 5.0
